Исключение, если не достигнуто целевое покрытие тестами

diff --git a/.github/workflows/code_quality.yml b/.github/workflows/code_quality.yml
--- a/.github/workflows/code_quality.yml
+++ b/.github/workflows/code_quality.yml
@@ -36,12 +36,20 @@ jobs:
           python-version: '3.11'
       - run: pip install poetry
       - run: poetry install --with test --without dev
-      - run: poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src --cov-fail-under=100 | tee pytest-coverage.txt
+      - name: Collect coverage
+        id: coverage
+        run: |
+          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src --cov-fail-under=100 | tee pytest-coverage.txt
+          cov_fail=`cat ./pytest-coverage.txt | grep 'not reached'`
+          echo "cov_fail=$cov_fail" >> $GITHUB_OUTPUT
+      - if: steps.coverage.outputs.cov_fail
+        run: exit 1
       - name: Coverage comment
         if: failure()
         uses: MishaKav/pytest-coverage-comment@main
         with:
           junitxml-path: ./pytest.xml
+          create-new-comment: true
   formatter:
     needs:
       - mypy
